### ISSUE TITLE
乌龟x64 1H1G小鸡 cpu-limit脚本运行过多

### ISSUE THREAD

**Issue by Erope** [spiritLHLS/Oracle-server-keep-alive-script#10]
![2023-02-08_10-33](https://user-images.githubusercontent.com/44471469/217414044-aaa3a871-8032-4786-a2f9-8edaa60d8961.png)

版本：2023.02.05

**Comment by Erope** [comment]
另外卸载脚本里面的 pgrep 命令用法有些问题，pgrep 无法筛选命令参数，可以用这个
kill $(ps -efA | grep cpu-limit.sh | awk '{print $2}')

**Comment by Erope** [comment]
> > 另外卸载脚本里面的 pgrep 命令用法有些问题，pgrep 无法筛选命令参数，可以用这个 kill $(ps -efA | grep cpu-limit.sh | awk '{print $2}')
> 
> 感谢指出错误
> 
> > ![2023-02-08_10-33](https://user-images.githubusercontent.com/44471469/217414044-aaa3a871-8032-4786-a2f9-8edaa60d8961.png)
> > 版本：2023.02.05
> 
> 但占用方面没问题吧，觉得多我塞个wait得了

有问题，一个bash占将近2M内存，500个快把1G内存吃满了

**Comment by spiritLHLS** [comment]
> > > 另外卸载脚本里面的 pgrep 命令用法有些问题，pgrep 无法筛选命令参数，可以用这个 kill $(ps -efA | grep cpu-limit.sh | awk '{print $2}')
> > 
> > 
> > 感谢指出错误
> > > ![2023-02-08_10-33](https://user-images.githubusercontent.com/44471469/217414044-aaa3a871-8032-4786-a2f9-8edaa60d8961.png)
> > > 版本：2023.02.05
> > 
> > 
> > 但占用方面没问题吧，觉得多我塞个wait得了
> 
> 有问题，一个bash占将近2M内存，500个快把1G内存吃满了

草，行吧，我改成wait

**Comment by spiritLHLS** [comment]
> > > 另外卸载脚本里面的 pgrep 命令用法有些问题，pgrep 无法筛选命令参数，可以用这个 kill $(ps -efA | grep cpu-limit.sh | awk '{print $2}')
> > 
> > 
> > 感谢指出错误
> > > ![2023-02-08_10-33](https://user-images.githubusercontent.com/44471469/217414044-aaa3a871-8032-4786-a2f9-8edaa60d8961.png)
> > > 版本：2023.02.05
> > 
> > 
> > 但占用方面没问题吧，觉得多我塞个wait得了
> 
> 有问题，一个bash占将近2M内存，500个快把1G内存吃满了

改成wait等待执行完毕再执行下一个了

**Comment by Erope** [comment]
> 

行，那我先close了

**Comment by spiritLHLS** [comment]
> > 
> 
> 行，那我先close了

不是wait的问题，是systemd在自动重启任务时没有将残余的进程kill掉，我增加了kill的部分，现在应该不会自动重启任务时还保留前面残余的进程了

**Comment by spiritLHLS** [comment]
![图片](https://user-images.githubusercontent.com/103393591/217519670-68a85411-269f-44cb-8b5c-1013dd348697.png)
运行了几个小时，好像不会新增bash了，应该解决问题了

**Comment by Erope** [comment]
> 

挺好，有空我把鸡都更新下

**Comment by Erope** [comment]
有一个鸡...好像还是有亿点点问题...现在已经760个进程了
建议在cpu-limit.sh运行前判断下有没有正在运行的，可以kill掉再继续运行

**Comment by spiritLHLS** [comment]
绝活，我再看看

**Comment by spiritLHLS** [comment]
> 有一个鸡...好像还是有亿点点问题...现在已经760个进程了 建议在cpu-limit.sh运行前判断下有没有正在运行的，可以kill掉再继续运行

更新了，我专门搞了个 /tmp/cpu-limit.pid 记录pid，可以更新过段时间看看 cat /tmp/cpu-limit.pid 和 pidof bash 对应一下看看哪里出的问题

**Comment by spiritLHLS** [comment]
同理增加了 /tmp/memory-limit.pid 和 /tmp/bandwidth_occupier.pid ，如果哪一个有问题后续会有记录了

**Comment by spiritLHLS** [comment]
![图片](https://user-images.githubusercontent.com/103393591/220145719-031bc656-3ce6-4ab1-959a-d008e3246dcb.png)

2小时过去后我这边好像没增加，等你测试你的了

**Comment by spiritLHLS** [comment]
![图片](https://user-images.githubusercontent.com/103393591/220223430-0ecb860c-064f-40e9-b46e-47ce2052818f.png)
第二天也没问题

**Comment by Wittoy** [comment]
![image](https://user-images.githubusercontent.com/22721456/220237947-e5112069-c07a-4b95-8d8c-f44f3d621b6d.png)
负载已经破百了（
`2023.02.20.21.04`

**Comment by Erope** [comment]
> 

OK，我测一下
不过上面那个老哥可能已经复现了

**Comment by spiritLHLS** [comment]
> `2023.02.20.21.04`
> 
> ![image](https://user-images.githubusercontent.com/22721456/220237947-e5112069-c07a-4b95-8d8c-f44f3d621b6d.png) 负载已经破百了（
> 
> Systemd
> 
> ![image](https://user-images.githubusercontent.com/22721456/220238643-2d17792d-7fc1-470f-be7a-d03ce1346058.png)

6，这里还能出问题是吧，看来还是得加东西限制service，只在sh中限制还不够

**Comment by spiritLHLS** [comment]
![图片](https://user-images.githubusercontent.com/103393591/220244115-dc216a37-bfde-47cd-bc97-1082dba396d2.png)
我跑了一晚上就两，有点奇怪amd的龟壳为什么会生成这么多

**Comment by spiritLHLS** [comment]
> `2023.02.20.21.04`
> 
> ![image](https://user-images.githubusercontent.com/22721456/220237947-e5112069-c07a-4b95-8d8c-f44f3d621b6d.png) 负载已经破百了（
> 
> Systemd
> 
> ![image](https://user-images.githubusercontent.com/22721456/220238643-2d17792d-7fc1-470f-be7a-d03ce1346058.png)

我在service中和执行的shell中都设置有pid查询和kill了，如果还有问题，那我只能想想别的法子了

**Comment by Erope** [comment]
> > `2023.02.20.21.04`
> > ![image](https://user-images.githubusercontent.com/22721456/220237947-e5112069-c07a-4b95-8d8c-f44f3d621b6d.png) 负载已经破百了（
> > Systemd
> > ![image](https://user-images.githubusercontent.com/22721456/220238643-2d17792d-7fc1-470f-be7a-d03ce1346058.png)
> 
> 我在service中和执行的shell中都设置有pid查询和kill了，如果还有问题，那我只能想想别的法子了

我也复现了，虽然我也搞不清楚为啥...

**Comment by spiritLHLS** [comment]
> > 我在service中和执行的shell中都设置有pid查询和kill了，如果还有问题，那我只能想想别的法子了
> 
> 更新 [3a048dc](https://github.com/spiritLHLS/Oracle-server-keep-alive-script/commit/3a048dc88f499c8bad7c016c3ad6efe14f61de49) 之后 arm64 debian 11, 2h30m只有6个, debian 11是手动安装的 amd64 ubuntu 22.04, 1h10m又几十个了, ubuntu 22.04是用的oracle cloud自带的镜像 两台amd都是这样
> 
> arm: ![image](https://user-images.githubusercontent.com/40228052/220301433-6bb72b0a-465b-4e99-8f5a-282cfe81ad79.png)
> 
> amd1: ![image](https://user-images.githubusercontent.com/40228052/220301671-fb0a402f-e22a-4e7d-863c-9fbae2711218.png)
> 
> amd2: ![image](https://user-images.githubusercontent.com/40228052/220301817-16f16b2c-648a-4f78-9966-1269537918ba.png)

看样子还是有问题阿，我在别的机器上实验是没问题的，我琢磨琢磨别的法子吧

**Comment by spiritLHLS** [comment]
@Weltolk 我弃用了素数计算，全部使用dd进行占用，观察到arm方面这块不再新增更多pid，并使用ulimit -u 10限制最大子进程10，再重装测测试试？思来想去只能是这块有问题了

**Comment by Erope** [comment]
测了一天，看起来没什么问题了，Issue先关了，有问题再开

**Comment by spiritLHLS** [comment]
OK, 我改改主脚本描述, 有问题再说
