### ISSUE TITLE
能不能加一个一键更新的功能？

### ISSUE THREAD

**Issue by lukemin** [spiritLHLS/Oracle-server-keep-alive-script#12]
能不能加一个一键更新的功能？

**Comment by spiritLHLS** [comment]
晚上琢磨琢磨我看看吧

**Comment by spiritLHLS** [comment]
![图片](https://user-images.githubusercontent.com/103393591/218264453-da467866-b4b0-44e3-ac2d-1e634b14cfba.png)
已解决
