### ISSUE TITLE
如果安装了来自speedtest官方源的cli程序，会导致无法安装Ubuntu等发行源的speedtest-cli程序

### ISSUE THREAD

**Issue by Erope** [spiritLHLS/Oracle-server-keep-alive-script#13]
如果安装了来自speedtest官方源的cli程序，会导致无法安装Ubuntu等发行源的speedtest-cli程序
https://www.speedtest.net/apps/cli

**Comment by Erope** [comment]
还有一个小问题，apt在安装包之前不会自动update，可以考虑在运行的时候先update下，防止包信息过期

**Comment by spiritLHLS** [comment]
ok，稍后修复

**Comment by spiritLHLS** [comment]
![图片](https://user-images.githubusercontent.com/103393591/218264477-28220d53-ae84-48d1-84ab-3b20ef503267.png)
已解决增加update
