### ISSUE TITLE
默认内存占用都好高啊

### ISSUE THREAD

**Issue by wxdjs** [spiritLHLS/Oracle-server-keep-alive-script#18]
很多都超出40%了

**Comment by spiritLHLS** [comment]
能否截图？
htop或者top
还有这些命令的截图
```
cat /tmp/memory-limit.pid
cat /tmp/cpu-limit.pid
cat /tmp/bandwidth_occupier.pid
pidof bash
service cpu-limit status
```
按理说不会有bug，距离上次修BUG过去一周了

**Comment by wxdjs** [comment]
不好意思，可能搞混了，看到了amd的内存占用，我在amd机器上脚本没启用内存占用，是不是脚本服务占的内存比较多？
arm机器正常的

**Comment by spiritLHLS** [comment]
你得输入我给你的这些命令查看，按理说不会超限的，有写检测，你可以截图直接粘贴到评论中，会自动上传GitHub的，不看这些查询输出我不知道你的问题在哪里
