### ISSUE TITLE
能否在脚本中自定义带宽占用间隔时间、文件大小、带宽网速

### ISSUE THREAD

**Issue by DeeEi** [spiritLHLS/Oracle-server-keep-alive-script#2]
原脚本是带宽占用每30分钟下载一次1G~10G大小的文件进行占用，占用20%的总网速。

想自定义间隔时间、文件大小、带宽网速。

**Comment by spiritLHLS** [comment]
后续增加吧，在修CPU占用的问题，AMD的IO-wait高了不行

**Comment by spiritLHLS** [comment]
搓好了，自定义需要在最后选择自定义为y，开始自定义设置
