### ISSUE TITLE
Red Hat系列无法安装`speedtest-cli`

### ISSUE THREAD

**Issue by Astro-Lee** [spiritLHLS/Oracle-server-keep-alive-script#20]
https://github.com/spiritLHLS/Oracle-server-keep-alive-script/blob/5f22f18948e859ffc16641be1b8e22f2bfabf1df/oalive.sh#L119-L127
报错如下：
![image](https://user-images.githubusercontent.com/61745903/222896573-86c1c2c0-9eda-423a-98ba-0939702918c6.png)

希望作者能优化一下脚本，谢谢！

**Comment by spiritLHLS** [comment]
明晚修复，今天太晚了

**Comment by Astro-Lee** [comment]
好的，谢谢！

**Comment by Astro-Lee** [comment]
可以尝试一下这两个解决方案：

1. [speedtest](https://www.speedtest.net/zh-Hans/apps/cli#fedora)

2.[speedtest-go](https://github.com/showwin/speedtest-go)

**Comment by spiritLHLS** [comment]
已修复，安装epel-release后再安装就没问题了

https://github.com/spiritLHLS/Oracle-server-keep-alive-script/commit/c711e2a97e1eafe544718bc6776559c89c5eac1b

**Comment by Astro-Lee** [comment]
1.我安装了`epel-release`, 但epel里并没有`speedtest-cli`, 如下图
![image](https://user-images.githubusercontent.com/61745903/222961103-c7af927d-e4bb-4ff4-b298-9ba2f7ff61de.png)

2.我尝试安装ookla的`speedtest`, 但该命令没有参数`--simple`，仅使用命令`speedtest`也能测速，但需要安装
![image](https://user-images.githubusercontent.com/61745903/222961139-b0cc887a-371b-410e-a587-854152dda346.png)
![image](https://user-images.githubusercontent.com/61745903/222961366-970d8c96-1860-4c9e-b072-085abe752c15.png)

3.我使用了 [speedtest-go](https://github.com/showwin/speedtest-go) 项目的二进制文件进行测速，免安装，移植性好，能否考虑用该软件测试带宽？
![image](https://user-images.githubusercontent.com/61745903/222961592-17562a60-b8a4-4dad-b283-13d0fc7c2ec0.png)

**Comment by spiritLHLS** [comment]
好吧，看来有的系统还是没能安装上，早上起来我有空再塞个判断吧，如果还是安装不上就用go版本作为补充替代方案，再打个补丁

**Comment by spiritLHLS** [comment]
> 1.我安装了`epel-release`, 但epel里并没有`speedtest-cli`, 如下图 ![image](https://user-images.githubusercontent.com/61745903/222961103-c7af927d-e4bb-4ff4-b298-9ba2f7ff61de.png)
> 
> 2.我尝试安装ookla的`speedtest`, 但该命令没有参数`--simple`，仅使用命令`speedtest`也能测速，但需要安装 ![image](https://user-images.githubusercontent.com/61745903/222961139-b0cc887a-371b-410e-a587-854152dda346.png) ![image](https://user-images.githubusercontent.com/61745903/222961366-970d8c96-1860-4c9e-b072-085abe752c15.png)
> 
> 3.我使用了 [speedtest-go](https://github.com/showwin/speedtest-go) 项目的二进制文件进行测速，免安装，移植性好，也可放到容器中减少体积，能否考虑用该软件测试带宽？ ![image](https://user-images.githubusercontent.com/61745903/222961592-17562a60-b8a4-4dad-b283-13d0fc7c2ec0.png)

麻烦执行一下```yum repolist all```我看看有什么库？你是使用官方订阅的源还是别的第三方系统的源？

**Comment by Astro-Lee** [comment]
![image](https://user-images.githubusercontent.com/61745903/223013918-15787c44-2b83-4a27-9af5-6b1d6999a167.png)
系统`Almalinux 9.1`

**Comment by spiritLHLS** [comment]
已修复

https://github.com/spiritLHLS/Oracle-server-keep-alive-script/commit/ee564f9223f3d65391c31785713bd6b7859a707a

https://github.com/spiritLHLS/Oracle-server-keep-alive-script/commit/b378f32d891d5339027816f57bde02ee2e724707
