### ISSUE TITLE
脚本安装后是一直在后台运行吗

### ISSUE THREAD

**Issue by anxiang** [spiritLHLS/Oracle-server-keep-alive-script#21]
请问脚本安装完成后，如果不执行选项2和选项3，会一直在后台运行吗？
一直后台运行的话，就能满足甲骨文的3条规则，就不会被甲骨文停机了？

**Comment by spiritLHLS** [comment]
保活服务只是占用资源，至于是否会被甲骨文停机我也说不准，但目前没有人反馈说使用本脚本7天后还收到邮件说最近7天闲置机器的
