### ISSUE TITLE
 2023.03.06.12.44，一樣造成 caddy(非容器) 服務死掉 疑似 systemctl 问题

### ISSUE THREAD

**Issue by Lawlietr** [spiritLHLS/Oracle-server-keep-alive-script#23]
昨天太晚了，已經眼花
今天檢查，其實昨天 caddy 服務確實是死了
今天升級 2023.03.06.12.44，一樣造成 caddy 服務死掉

```
Mar 06 14:22:30 o3 caddy[680623]: {"level":"info","ts":1678083750.0312257,"msg":"shutting down apps, then terminating","signal":"SIGTERM"}
Mar 06 14:22:30 o3 caddy[680623]: {"level":"warn","ts":1678083750.0321887,"msg":"exiting; byeee!! 👋","signal":"SIGTERM"}
Mar 06 14:22:30 o3 caddy[680623]: {"level":"info","ts":1678083750.0413914,"logger":"tls.cache.maintenance","msg":"stopped background certificate>Mar 06 14:22:30 o3 caddy[680623]: {"level":"info","ts":1678083750.0425074,"logger":"admin","msg":"stopped previous server","address":"localhost:>Mar 06 14:22:30 o3 caddy[680623]: {"level":"info","ts":1678083750.0425303,"msg":"shutdown complete","signal":"SIGTERM","exit_code":0}
Mar 06 14:22:30 o3 systemd[1]: caddy.service: Succeeded.
```

_Originally posted by @Lawlietr in https://github.com/spiritLHLS/Oracle-server-keep-alive-script/issues/22#issuecomment-1455531649_

**Comment by spiritLHLS** [comment]
好吧，我复现一下看看啥问题

**Comment by spiritLHLS** [comment]
> > 好吧，我复现一下看看啥问题
> 
> 请问升级就只需要点升级脚本就行了？需要卸载重装不？

升级只是升级了安装脚本本体，你需要重新设置占用

**Comment by hecarli555** [comment]
> 好吧，我复现一下看看啥问题

请问大佬问题修复好了么？

**Comment by spiritLHLS** [comment]
有反馈容器版本的caddy不会有这个问题

**Comment by Lawlietr** [comment]
> 有人反馈容器版本的caddy不会有这个问题

我在甲骨文總共三台機器
跟大部分人一樣
共兩台 x86, 一台 arm

x86 的兩台使用 Centos7 跟 Caddy 1.0.x
amr 使用 Ubuntu 20.04 跟 Caddy 2.0.x

上面提供的訊息是 amr 這台
這台平常使用記憶體大約在 2GB 
使用 keep alive 後，會在 systemctl daemom 信息中發現進程被系統中止
不過 DMESG 此時沒有產生任何信息，RAM 使用率看起來也正常

CentOS 7 兩台都是自己編譯的 Caddy
沒接上 systemctl，死掉的時候茶找不到任何信息，包括 DMESG

我猜這有可能是 systemctl 的 bug
目前在想要怎麼提交
因為我自己看半天，也是不覺得這個 keep alive 會造成此種問題
