### ISSUE TITLE
Oracle-Linux-8.7安装带宽占用时报错Failed to start bandwidth_occupier.timer: Unit bandwidth_occupier.timer not found

### ISSUE THREAD

**Issue by we125182** [spiritLHLS/Oracle-server-keep-alive-script#24]
```bash
需要自定义带宽占用的设置吗? (y/[n])

使用默认配置，45分钟间隔，请求10分钟，请求速率为最大速度的20%
Failed to start bandwidth_occupier.timer: Unit bandwidth_occupier.timer not found.
Failed to enable unit: Unit file bandwidth_occupier.timer does not exist.
带宽限制安装成功 脚本路径: /usr/local/bin/bandwidth_occupier.sh
The bandwidth limit script has been installed at /usr/local/bin/bandwidth_occupier.sh
```

**Comment by we125182** [comment]
cpu和内存也是报一样的错
```
Failed to enable unit: Unit file cpu-limit.service does not exist.
Failed to start cpu-limit.service: Unit cpu-limit.service not found.
CPU限制安装成功 脚本路径: /usr/local/bin/cpu-limit.sh
The CPU limit script has been installed at /usr/local/bin/cpu-limit.sh

...

Failed to enable unit: Unit file memory-limit.service does not exist.
Failed to start memory-limit.service: Unit memory-limit.service not found.
内存限制安装成功 脚本路径: /usr/local/bin/memory-limit.sh
The memory limit script has been installed at /usr/local/bin/memory-limit.sh
```

映像:
 
[Oracle-Linux-8.7-aarch64-2023.01.31-3](https://cloud.oracle.com/compute/images/ocid1.image.oc1.ap-chuncheon-1.aaaaaaaause5x5f54itmugu5dtatjz3omeh2u7mepvia6n6p64hmgticpfua)

**Comment by spiritLHLS** [comment]
好家伙还有用8.x的阿，行吧，有空我适配一下

**Comment by spiritLHLS** [comment]
我这边测试的好像没这个问题，你安装成功后可否查看一下
```
/etc/systemd/system/
```
目录下有没有 cpu-limit.service 和 memory-limit.service 文件？

**Comment by we125182** [comment]
<img width="1146" alt="image" src="https://user-images.githubusercontent.com/17947588/224254263-eed4a759-ce14-42f5-9ba8-d9e8df613fb2.png">
都存在，不清楚什么情况。不行的话，只能换系统了😭

**Comment by we125182** [comment]
这几个service的状态都是bad
<img width="632" alt="image" src="https://user-images.githubusercontent.com/17947588/224256560-119e76ae-62a9-4819-a05b-68f6d77adcaa.png">

**Comment by spiritLHLS** [comment]
你执行一下
```
sudo systemctl daemon-reload
sudo systemctl reset-failed
sudo systemctl daemon-reexec
```
然后再执行一下
```
systemctl list-unit-files | grep cpu-limit.service
sudo systemctl enable cpu-limit.service
```
看看是否有什么报错或者显示异常，如果正常的话执行
```
service cpu-limit status
```
看看服务是否活着

**Comment by we125182** [comment]
`sudo systemctl enable cpu-limit.service`这里就报错了
<img width="759" alt="image" src="https://user-images.githubusercontent.com/17947588/224271729-8068cfdc-470f-4bc0-9951-e8f1d5764c50.png">

**Comment by spiritLHLS** [comment]
好的，晚上我更新加上一个检测补丁，如果之前的服务启动失败将执行你这部分代码再次尝试启动

**Comment by spiritLHLS** [comment]
https://github.com/spiritLHLS/Oracle-server-keep-alive-script/commit/b2e0accb420e701d07c1a97a3409851e07696508

已更新补丁
