### ISSUE TITLE
2023.03.06.12.44版本，Ubuntu 20.04.4 LTS aarch64(Py3.7.8) 4核24G内存默认安装选项，安装后只有CPU有效果，内存跟网络都没有变化

### ISSUE THREAD

**Issue by thexxs** [spiritLHLS/Oracle-server-keep-alive-script#26]

**Comment by thexxs** [comment]
> 

我用的是宝塔面板，内存跟网络都是没有变化，CPU就会动态占用

**Comment by spiritLHLS** [comment]
执行htop或者top截个图，网络是45分钟一次，你也可以截图一下网络监控图，看甲骨文后台那的监控会有的

**Comment by thexxs** [comment]
内存的
![image](https://user-images.githubusercontent.com/5483144/224229187-cf283b5e-703c-4120-a903-a5f95ba2631d.png)
网络的
![image](https://user-images.githubusercontent.com/5483144/224229290-740b0cb3-2a35-4280-964b-1f5c5649491f.png)

**Comment by spiritLHLS** [comment]
没毛病阿，一切正常，htop看和这个看准点，内存在宝塔不显示可能是 https://github.com/spiritLHLS/Oracle-server-keep-alive-script/issues/6#issuecomment-1426607108 同样的原因
