### ISSUE TITLE
建议调整 Updating package management sources 设置

### ISSUE THREAD

**Issue by derekwei** [spiritLHLS/Oracle-server-keep-alive-script#27]
**建议将 Updating package management sources 去除或单列为脚本的一个选项。** 不然每次启动脚本都要强制先 update 一下，非常占用时间。而且生产环境下，有很多 package 是不需要更新的，否则可能会出现诸多奇怪的问题。

**Comment by spiritLHLS** [comment]
晚上会更新一下，确实是个潜在问题

**Comment by spiritLHLS** [comment]
https://github.com/spiritLHLS/Oracle-server-keep-alive-script/commit/40703e87181d4e4a695b24468662a5cd17b72322

已修改更新完毕

![图片](https://user-images.githubusercontent.com/103393591/224294115-edf34d3d-620d-414c-8f2a-e2df935c7efb.png)

**Comment by spiritLHLS** [comment]
那是预下载epel包，不是update，这个不装后面服务装不上的，你没发现没有黄色提示了么？那个才是update

**Comment by spiritLHLS** [comment]
也行，晚上吧
