### ISSUE TITLE
2023.03.06.12.44版本，安装带宽限制时，提示“不支持该架构：aarch64”

### ISSUE THREAD

**Issue by Qingchenm** [spiritLHLS/Oracle-server-keep-alive-script#28]
报错情况如下，前两项安装成功，安装到第三项时 报错
请问该如何解决？
谢谢！

需要限制带宽吗? ([y]/n): y
speedtest-cli not found, installing...
Installing speedtest-cli
Updating package management sources
Failed to set locale, defaulting to C.UTF-8
Last metadata expiration check: 2:37:46 ago on Fri Mar 10 09:44:00 2023.
No match for argument: speedtest-cli
Error: Unable to find a match: speedtest-cli
不支持该架构：aarch64

**Comment by spiritLHLS** [comment]
不是不支持吧，是源没有装不动，我晚上加上一个补丁，安装不了就用go版本替代吧

**Comment by thexxs** [comment]
大佬内存占用不显示的确定没问题吗，我跑其他脚本内存是能上去的？顺便问一下，你这个查看监控的是什么
![image](https://user-images.githubusercontent.com/5483144/224241502-ca76975c-6384-4009-b5cb-177733346ec8.png)

**Comment by spiritLHLS** [comment]
> 大佬内存占用不显示的确定没问题吗，我跑其他脚本内存是能上去的？顺便问一下，你这个查看监控的是什么 ![image](https://user-images.githubusercontent.com/5483144/224241502-ca76975c-6384-4009-b5cb-177733346ec8.png)

nezha监控

https://user-images.githubusercontent.com/5483144/224229187-cf283b5e-703c-4120-a903-a5f95ba2631d.png

你自己发的这截图不是写了么，占用了4G内存，不信的话你可以甲骨文后台看或者命令行执行htop看

至于为啥宝塔不显示类同 https://github.com/spiritLHLS/Oracle-server-keep-alive-script/issues/6#issuecomment-1426607108

**Comment by spiritLHLS** [comment]
https://github.com/spiritLHLS/Oracle-server-keep-alive-script/commit/40703e87181d4e4a695b24468662a5cd17b72322

已修改更新完毕
