### ISSUE TITLE
可以定时跑吗？

### ISSUE THREAD

**Issue by sxml** [spiritLHLS/Oracle-server-keep-alive-script#30]
半夜不常用时间段 跑脚本？

**Comment by spiritLHLS** [comment]
阿哲，这没法控制吧，龟壳时区不一样的吧，换算成北京时间也麻烦

**Comment by javafast** [comment]
让用户自己输入当地时间的开始时间-结束时间？ 总比现在24小时一直跑 好吧？

**Comment by spiritLHLS** [comment]
> 让用户自己输入当地时间的开始时间-结束时间？ 总比现在24小时一直跑 好吧？

也不是24小时跑阿，有间隔，如果需要定时功能建议使用别的脚本
