### ISSUE TITLE
ocracle 定义Idle的具体规则是什么

### ISSUE THREAD

**Issue by matthuo333** [spiritLHLS/Oracle-server-keep-alive-script#31]
经过连续两天使用脚本，最终还是被oracle停用。所以对于规则到底是什么？

另外，关于脚本可否自行设定启停？自己加计划任务来做就好。否则自己的业务在用时，只能卸载。然后再用再安装，很麻烦。

P.S. 附被停用前的实际占用率

![image](https://user-images.githubusercontent.com/55862904/225204337-2900ea5d-c89e-490a-95f9-ff46d9d7dada.png)

**Comment by spiritLHLS** [comment]
实在需要定时的也好办，晚上我写个一键shell命令吧，就是很长很长(且分为启动和停止两个任务)，定时怎么定时就得你们各显神通了，crontab或者别的第三方定时器

占用2天可到达不了要求，因为2天内有间隔的占用，累计估计是不够甲骨文要求的

```
适用于甲骨文云计算的永久免费实例，计算周期为七天，七天内触发条件可能会被回收。

CPU闲置率：七天内的 95% 的时间，CPU使用率都低于10% 则服务器可能会被回收。

网络利用率：如果服务器的网络利用率低于10%则视为闲置机器，可能会被回收服务器。

内存利用率：此条仅适用于A1型(ARM)机器 , 内存利用率低于 10% 则视为闲置机器，可能会被回收服务器。
```

**Comment by spiritLHLS** [comment]
https://github.com/spiritLHLS/Oracle-server-keep-alive-script/blob/main/README_CRON.md

具体怎么设置任务你就去设置吧

**Comment by matthuo333** [comment]
感谢大神神速反馈！
但是使用分离的各脚本时，遇到两个问题，一个是启动每个脚本后，貌似都必须前台运行，占用当前终端； 另个 在内存占用脚本中，其中参数 size 是 设置占用内存大小么？ 这个默认是3+ G。 没注意，启动后，直接造成VPS I/O问题，必须重启机器了。

**Comment by spiritLHLS** [comment]
内存有占用要求的是ARM机器，12G内存的占3G够了吧，我改改说明

不必前台运行，都是shell命令，你定时任务后台运行也没毛病

**Comment by mclovin-2k** [comment]
> 实在需要定时的也好办，晚上我写个一键shell命令吧，就是很长很长(且分为启动和停止两个任务)，定时怎么定时就得你们各显神通了，crontab或者别的第三方定时器
> 
> 占用2天可到达不了要求，因为2天内有间隔的占用，累计估计是不够甲骨文要求的
> 
> ```
> 适用于甲骨文云计算的永久免费实例，计算周期为七天，七天内触发条件可能会被回收。
> 
> CPU闲置率：七天内的 95% 的时间，CPU使用率都低于10% 则服务器可能会被回收。
> 
> 网络利用率：如果服务器的网络利用率低于10%则视为闲置机器，可能会被回收服务器。
> 
> 内存利用率：此条仅适用于A1型(ARM)机器 , 内存利用率低于 10% 则视为闲置机器，可能会被回收服务器。
> ```

这些条件只要满足一条就会被回收吗？还是必须都满足才会被回收？
如果是后者的话，似乎不需要同时运行 CPU，内存，带宽3个脚本。

**Comment by spiritLHLS** [comment]
> > 实在需要定时的也好办，晚上我写个一键shell命令吧，就是很长很长(且分为启动和停止两个任务)，定时怎么定时就得你们各显神通了，crontab或者别的第三方定时器
> > 占用2天可到达不了要求，因为2天内有间隔的占用，累计估计是不够甲骨文要求的
> > ```
> > 适用于甲骨文云计算的永久免费实例，计算周期为七天，七天内触发条件可能会被回收。
> > 
> > CPU闲置率：七天内的 95% 的时间，CPU使用率都低于10% 则服务器可能会被回收。
> > 
> > 网络利用率：如果服务器的网络利用率低于10%则视为闲置机器，可能会被回收服务器。
> > 
> > 内存利用率：此条仅适用于A1型(ARM)机器 , 内存利用率低于 10% 则视为闲置机器，可能会被回收服务器。
> > ```
> 
> 这些条件只要满足一条就会被回收吗？还是必须都满足才会被回收？ 如果是后者的话，似乎不需要同时运行 CPU，内存，带宽3个脚本。

官方说明链接：

https://docs.oracle.com/en-us/iaas/Content/FreeTier/freetier_topic-Always_Free_Resources.htm#compute__idleinstances

怎么理解就是你的问题了，我目前没有收到提示
