### ISSUE TITLE
一个小小的显示优化建议

### ISSUE THREAD

**Issue by hecarli555** [spiritLHLS/Oracle-server-keep-alive-script#32]
能不能在载入脚本后显示当前CPU，内存，带宽是否在执行，要是还能显示当时安装的参数就更好了，例如“CPU占用：20%”这样，因为有时候都忘记了有没有装保护脚本了哈哈哈哈哈

**Comment by spiritLHLS** [comment]
后续塞个吧，等有空

**Comment by spiritLHLS** [comment]
已更新脚本主体，如果有问题再反馈吧
