### ISSUE TITLE
带宽占用自定义逻辑优化

### ISSUE THREAD

**Issue by bbeyes-github** [spiritLHLS/Oracle-server-keep-alive-script#33]
希望作者调整一下带宽占用选择自定义时的脚本逻辑。
在每个带宽占用周期，满速探测带宽时，短时间会对服务器的响应速度造成较大影响。希望改为：在选择自定义带宽占用的情况下，直接按照限速下载文件，无需使用speedtest进行测速，避免测速时影响网络流量。
谢谢！

**Comment by spiritLHLS** [comment]
晚点修复
