### ISSUE TITLE
貌似流量保活有问题

### ISSUE THREAD

**Issue by GithubNBR** [spiritLHLS/Oracle-server-keep-alive-script#34]
设置了自定义，怎么设都会有大流量进出，就算设10m带宽1小时一次，一天也会跑一两百g

**Comment by spiritLHLS** [comment]
晚点修复

**Comment by spiritLHLS** [comment]
已更新脚本主体，如果有问题再反馈吧

**Comment by GithubNBR** [comment]
还是有问题，现在用了流量不走了..

**Comment by spiritLHLS** [comment]
阿哲，晚点我看看

**Comment by jelly0925** [comment]
2023.03.20.20.36 这个版本一点流量都不跑，UP有空了看看哈，谢谢

**Comment by spiritLHLS** [comment]
修正了单位，应该没毛病了，重新设置一遍占用你测测看还有没有问题

**Comment by jelly0925** [comment]
早上重新安装了脚本，流量占用还是不正常呢

spiritLHLS ***@***.***> 于 2023年3月22日周三 21:58写道：

**Comment by spiritLHLS** [comment]
今晚修复，抱歉拖了这么久

**Comment by GithubNBR** [comment]
感谢大神

**Comment by spiritLHLS** [comment]
https://github.com/spiritLHLS/Oracle-server-keep-alive-script/commit/7fe64bd7433ad255f2e443c677a8e75d7f71ca66

修改不会出现空链接的情况了，如果一直超时将使用默认的cloudflare的测速文件进行带宽占用，应该没问题了，如果有问题再说吧，我测试的没问题，后台有显示了

![图片](https://user-images.githubusercontent.com/103393591/227713323-e48a493e-d1b3-4c35-869c-da397668a573.png)

**Comment by jelly0925** [comment]
UP刚刚把旧脚本及文件全部删除，重新安装设定了流量参数，目前bandwidth_occupier.service这个服务还是只跑几秒钟就自动退出，并且这个版本自定义流量参数后不生效。辛苦在排查一下，谢谢了
