### ISSUE TITLE
2023.03.20.20.36 版本的带宽占用有问题

### ISSUE THREAD

**Issue by jelly0925** [spiritLHLS/Oracle-server-keep-alive-script#35]
作者你好
      今天更新脚本到2023.03.20.20.36后，重新服务发现测速脚本不运行了，脚本更新几个小时后甲骨文实例流量一点都没有增加，希望修正一下，谢谢
![bug](https://user-images.githubusercontent.com/3022023/226851266-d4bdca99-9ab7-4bc0-8a7a-dfb0ac08a9de.png)

**Comment by spiritLHLS** [comment]
https://github.com/spiritLHLS/Oracle-server-keep-alive-script/issues/34

有人提出了，我还在看
