### ISSUE TITLE
啥时候可以出个docker版本的 

### ISSUE THREAD

**Issue by xiangchu95** [spiritLHLS/Oracle-server-keep-alive-script#37]

**Comment by spiritLHLS** [comment]
https://github.com/spiritLHLS/Oracle-server-keep-alive-script/issues/15

类似问题有人提过，但目前脚本还不能保证100%无BUG，还在测试观望

**Comment by chenzhenguo** [comment]
有必要吗？？

**Comment by spiritLHLS** [comment]
由于有朋友实测，感觉停机这回事过于玄学，故不准备再继续开发下去了，暂时就这样吧

**Comment by chenzhenguo** [comment]
邮件发送失败
