### ISSUE TITLE
bandwidth_occupier.service 刚启动就自动停止

### ISSUE THREAD

**Issue by jelly0925** [spiritLHLS/Oracle-server-keep-alive-script#38]
CGroup: /system.slice/bandwidth_occupier.service
             ├─135540 /bin/bash /usr/local/bin/bandwidth_occupier.sh
             ├─135542 timeout 5s wget --tries=3 --spider http://lg-kie.fdcservers.net/10GBtest.zip
             └─135543 wget --tries=3 --spider http://lg-kie.fdcservers.net/10GBtest.zip
一直连接超时，造成实例不跑流量
![Snipaste_2023-03-24_22-10-26](https://user-images.githubusercontent.com/3022023/227545240-74a39a62-89a0-4e94-b72f-a72cfcca697f.png)
![Snipaste_2023-03-24_22-13-02](https://user-images.githubusercontent.com/3022023/227546159-b32fa215-79ea-44bb-ac30-bb58f5577d05.png)

**Comment by spiritLHLS** [comment]
这是已知bug，前面的issues有提及，只是最近忙着修 
https://github.com/spiritLHLS/ecs#%E5%BE%85%E8%A7%A3%E5%86%B3%E4%BA%8B%E9%A1%B9 
里的测速节点，正在折腾自动获取测速服务器ID，没来得及修这个仓库的BUG，明天我看看吧

**Comment by spiritLHLS** [comment]
https://github.com/spiritLHLS/Oracle-server-keep-alive-script/commit/7fe64bd7433ad255f2e443c677a8e75d7f71ca66

修改不会出现空链接的情况了，如果一直超时将使用默认的cloudflare的测速文件进行带宽占用，应该没问题了，如果有问题再说吧，我测试的没问题，后台有显示了

![图片](https://user-images.githubusercontent.com/103393591/227713323-e48a493e-d1b3-4c35-869c-da397668a573.png)

**Comment by jelly0925** [comment]
自定义网络占用还是不起作用呢，13台实例更新了今晚最新脚本默认参数可以跑一小会流量但是很快就退出了，自定义网络占用不生效。
![Snipaste_2023-03-25_21-36-01](https://user-images.githubusercontent.com/3022023/227720516-f86632d8-fe9d-4a24-92a4-e34257fe5bb3.png)

**Comment by GithubNBR** [comment]
还是不行，不管自动还是自定义设置，偶尔跑一下，大部分时间都不跑
新加坡amd
