### ISSUE TITLE
cup、内存、流量等3项都要满足才能保鸡吗？

### ISSUE THREAD

**Issue by gnz1123** [spiritLHLS/Oracle-server-keep-alive-script#4]
如果只需要满足其中一项，建议把流量的删除
建议增加停止和启动项，而不需要卸载才停止

**Comment by spiritLHLS** [comment]
安装时有询问是否要安装流量限制，你安装时不安装就行了
至于是不是三项都满足自己判别，我都写了，自己灵活安装即可，我不会强行要求全部安装
