### ISSUE TITLE
有方法可以 ansible 直接運行嗎?

### ISSUE THREAD

**Issue by mcdullmedia** [spiritLHLS/Oracle-server-keep-alive-script#41]
我的vm為方便管理, 可以 ansible 批量運行, [Oracle-server-keep-alive-script] 是否可以不用 interactive?
而最好 Oracle-server-keep-alive-script 能夠隨意更改名稱 以防 oracle 的agent 探查...

**Comment by spiritLHLS** [comment]
我没用过Ansible，这方面只能自行摸索了，如果是大批量使用，建议使用定时任务，形如 https://gitlab.com/spiritysdx/Oracle-server-keep-alive-script/-/blob/main/%20README_CRON.md ，这样你可以自行定义更多东西

本套脚本最初并没有考虑批量的问题，后续集成为docker后也许会有所改善
