### ISSUE TITLE
最新版的又出bug了

### ISSUE THREAD

**Issue by hecarli555** [spiritLHLS/Oracle-server-keep-alive-script#42]
最新版的又出bug了，内存占用并未生效，机器为首尔arm，更新脚本并重新安装最新脚本
![1679919987888](https://user-images.githubusercontent.com/76683744/227941172-2190e042-196e-43bf-b2ed-37468bbb52cc.png)

**Comment by spiritLHLS** [comment]
这不是BUG，你这显示的不显示缓存的，你需要htop或者top查看
