### ISSUE TITLE
占用内存并未生效

### ISSUE THREAD

**Issue by hecarli555** [spiritLHLS/Oracle-server-keep-alive-script#43]
占用内存并未生效，已经更新脚本并重新安装了，机器为首尔arm
![1679920153651](https://user-images.githubusercontent.com/76683744/227941653-cf29efaf-3a3d-4c48-9119-193a534618d3.png)

**Comment by spiritLHLS** [comment]
这不是BUG，你需要执行htop或者top查看，或者在甲骨文后台查看，finalshell不显示缓存的

**Comment by hecarli555** [comment]
不对吧。。。。怎么我记得以前装完内存占用后，左上角马上就占用起来了。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月27日(星期一) 晚上8:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [spiritLHLS/Oracle-server-keep-alive-script] 占用内存并未生效 (Issue #43)





 
这不是BUG，你需要执行htop或者top查看，或者在甲骨文后台查看，finalshell不显示缓存的

**Comment by spiritLHLS** [comment]
你执行htop之类的就能看到了，跑跑看看截图
