### ISSUE TITLE
cpu 占用好象不是动态吧

### ISSUE THREAD

**Issue by listenfree** [spiritLHLS/Oracle-server-keep-alive-script#47]
我在编译固件时，cpu  dd还在执行，亲，有空指点一下。

**Comment by spiritLHLS** [comment]
过去是动态的，但之前出现过CPU占用频繁更换进程导致残余进程占用大量内存的情况，就更改了写法写死了

**Comment by spiritLHLS** [comment]
https://github.com/spiritLHLS/Oracle-server-keep-alive-script/commit/c0410d579ec5e10662b6d6fad63b59048dd35605

已更新说明
