### ISSUE TITLE
wget好像不能用

### ISSUE THREAD

**Issue by yxmyxmyyy** [spiritLHLS/Oracle-server-keep-alive-script#49]
Created symlink /etc/systemd/system/timers.target.wants/bandwidth_occupier.timer → /etc/systemd/system/bandwidth_occupier.timer.
Failed to start bandwidth_occupier.timer: Unit bandwidth_occupier.timer has a bad unit file setting.
See system logs and 'systemctl status bandwidth_occupier.timer' for details.
oalive.sh: line 198: restorecon: command not found
oalive.sh: line 199: restorecon: command not found
Failed to start bandwidth_occupier.timer: Unit bandwidth_occupier.timer has a bad unit file setting.
See system logs and 'systemctl status bandwidth_occupier.timer' for details.
带宽限制安装成功 脚本路径: /usr/local/bin/bandwidth_occupier.sh
The bandwidth limit script has been installed at /usr/local/bin/bandwidth_occupier.sh

**Comment by yxmyxmyyy** [comment]
○ bandwidth_occupier.timer - Run the Bandwidth Occupier every 45 minutes
     Loaded: bad-setting (Reason: Unit bandwidth_occupier.timer has a bad unit file setting.)
     Active: inactive (dead)
    Trigger: n/a
   Triggers: ● bandwidth_occupier.service

Jun 05 18:42:20 ubuntu systemd[1]: bandwidth_occupier.timer: Timer unit lacks value setting. Refusing.
Jun 05 18:42:21 ubuntu systemd[1]: bandwidth_occupier.timer: Timer unit lacks value setting. Refusing.
Jun 05 18:42:21 ubuntu systemd[1]: bandwidth_occupier.timer: Timer unit lacks value setting. Refusing.
Jun 05 18:43:02 ubuntu systemd[1]: bandwidth_occupier.timer: Timer unit lacks value setting. Refusing.
Jun 05 18:43:02 ubuntu systemd[1]: bandwidth_occupier.timer: Timer unit lacks value setting. Refusing.
Jun 05 18:46:20 ubuntu systemd[1]: bandwidth_occupier.timer: Timer unit lacks value setting. Refusing.
Jun 05 18:46:20 ubuntu systemd[1]: bandwidth_occupier.timer: Timer unit lacks value setting. Refusing.
Jun 05 18:46:21 ubuntu systemd[1]: bandwidth_occupier.timer: Timer unit lacks value setting. Refusing.
Jun 06 13:44:49 ubuntu systemd[1]: bandwidth_occupier.timer: Timer unit lacks value setting. Refusing.
Jun 06 13:44:49 ubuntu systemd[1]: bandwidth_occupier.timer: Timer unit lacks value setting. Refusing.
这是圣何塞arm
● bandwidth_occupier.timer - Run the Bandwidth Occupier every 45 minutes
     Loaded: loaded (/etc/systemd/system/bandwidth_occupier.timer; enabled; vendor preset: enabled)
     Active: active (waiting) since Mon 2023-06-05 17:01:47 CST; 20h ago
    Trigger: Tue 2023-06-06 13:45:45 CST; 12s left
   Triggers: ● bandwidth_occupier.service

Jun 05 17:01:47 ubuntu systemd[1]: Started Run the Bandwidth Occupier every 45 minutes.
这是圣何塞amd
貌似都没有生效，两台机器都dd过，怕甲骨文通过网络接口监控宽带

**Comment by spiritLHLS** [comment]
```
cat /etc/systemd/system/bandwidth_occupier.timer
```

看看配置文件，应该是有配置错误的地方，这是arm的报错的原因


amd没啥问题，正常触发了

此外，在 

https://github.com/spiritLHLS/Oracle-server-keep-alive-script/issues/29

有说明DD的相关事情，如果DD后很可能已经无法监控资源了，不清楚占用是否还有效
