### ISSUE TITLE
模拟下载似乎未执行

### ISSUE THREAD

**Issue by MrZhengI** [spiritLHLS/Oracle-server-keep-alive-script#51]
![image](https://github.com/spiritLHLS/Oracle-server-keep-alive-script/assets/50481340/f5e9a6d6-d842-44db-b28c-ceceb7b15bdb)
![image](https://github.com/spiritLHLS/Oracle-server-keep-alive-script/assets/50481340/71a241d5-c444-4303-a477-4057646d91dd)
![image](https://github.com/spiritLHLS/Oracle-server-keep-alive-script/assets/50481340/90925e09-d971-42b3-acd0-6a94379e98af)

**Comment by spiritLHLS** [comment]
别只放图，自己看issues置顶说明，截图日志给我

**Comment by MrZhengI** [comment]
> 别只放图，自己看问题置顶说明，截图日志给我

![image](https://github.com/spiritLHLS/Oracle-server-keep-alive-script/assets/50481340/bb9f1449-9c34-42e5-9b61-3061b2ee72c6)
![image](https://github.com/spiritLHLS/Oracle-server-keep-alive-script/assets/50481340/025f2b50-fdca-4d08-a27d-11297f696f17)

**Comment by MrZhengI** [comment]
> centos系不兼容我守护进程的写法么，这个报错没见过，有没有系统信息？什么架构和什么系统

Linux localhost.localdomain 4.18.0-500.el8.aarch64 #1 SMP Wed Jun 28 00:12:09 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

**Comment by MrZhengI** [comment]
> centos系不兼容我守护进程的写法么，这个报错没见过，有没有系统信息？什么架构和什么系统

centos 8

**Comment by spiritLHLS** [comment]
该系统暂时没法通过守护进程解决，建议移步自定义的定时任务解决
