### ISSUE TITLE
甲骨文要求更新了，利用率要大于 20%

### ISSUE THREAD

**Issue by 404gods** [spiritLHLS/Oracle-server-keep-alive-script#52]
甲骨文要求更新了，以前是15%，现在利用率要大于 20%，作者大佬脚本也更新下吧20-25%比较合适了

**Comment by spiritLHLS** [comment]
https://github.com/spiritLHLS/Oracle-server-keep-alive-script/commit/899defb33aafdab2a72f89d953a56eb8353f38db

Done
