### ISSUE TITLE
查看 bandwidth_occupier.service，发现状态为inactive，这样的状态是正常运行了带宽限制功能么？

### ISSUE THREAD

**Issue by xorxorxorxor** [spiritLHLS/Oracle-server-keep-alive-script#55]
`systemctl status bandwidth_occupier.service`

> ● bandwidth_occupier.service - Bandwidth Occupier Service
>    Loaded: loaded (/etc/systemd/system/bandwidth_occupier.service; disabled; vendor preset: disabled)
>    Active: inactive (dead) since Sat 2023-10-07 07:21:26 GMT; 40min ago
>   Process: 28304 ExecStart=/bin/bash /usr/local/bin/bandwidth_occupier.sh (code=exited, status=0/SUCCESS)
>  Main PID: 28304 (code=exited, status=0/SUCCESS)
> 
> Oct 07 07:20:58 host2 systemd[1]: Started Bandwidth Occupier Service.
> Oct 07 07:20:58 host2 bash[28304]: /usr/local/bin/bandwidth_occupier.sh: line 11: warning: setlocale...TF-8)
> Oct 07 07:20:58 host2 bash[28304]: /usr/local/bin/bandwidth_occupier.sh: line 11: warning: setlocale...TF-8)
> Oct 07 07:21:02 host2 bash[28304]: /bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
> Oct 07 07:21:26 host2 bash[28304]: --2023-10-07 07:21:26--  http://lg-hou.fdcservers.net/10GBtest.zip
> Oct 07 07:21:26 host2 bash[28304]: Resolving lg-hou.fdcservers.net (lg-hou.fdcservers.net)... 23.237.164.248
> Oct 07 07:21:26 host2 bash[28304]: Connecting to lg-hou.fdcservers.net (lg-hou.fdcservers.net)|23.23...80...
> Hint: Some lines were ellipsized, use -l to show in full.

**Comment by spiritLHLS** [comment]
bandwidth_occupier.service 受 bandwidth_occupier.timer 控制 你后台监控到流量正常消耗了就行
