### ISSUE TITLE
关于甲骨文“一键dd”后是否就不会被关停？

### ISSUE THREAD

**Issue by hecarli555** [spiritLHLS/Oracle-server-keep-alive-script#58]
大佬想请教一下，“由于友人实测，资源占用感觉也是玄学，一个号四个服务器全部停机，但号还在，也有人一直不占用，但就是没停机的问题，所以该项目将长期保持现有状态，非必要不再更新”这里说的4个机器，是用的甲骨文自带的系统还是一键dd后的系统呢？好像说一键dd后就不会停机？

**Comment by spiritLHLS** [comment]
没听说过这种说法，朋友测试的是没DD的，但还是停机了

**Comment by hecarli555** [comment]
> 没听说过这种说法，朋友测试的是没DD的，但还是停机了

没dd那肯定停啊。。。。原版系统里面都带甲骨文监控的嘛
