### ISSUE TITLE
hostloc有几个水友反应arm占用不足

### ISSUE THREAD

**Issue by GithubNBR** [spiritLHLS/Oracle-server-keep-alive-script#6]
amd没问题，挺好的

**Comment by spiritLHLS** [comment]
arm还不够阿？阿哲，观察时间超过10分钟了还是这样么？

**Comment by spiritLHLS** [comment]
真不行只能塞虚拟化检测识别是arm的调高初始化参数了，晚上我改改

**Comment by spiritLHLS** [comment]
说说是哪方面不足，我改改

**Comment by spiritLHLS** [comment]
增加了CPU占用识别本机架构，是arm的我调大了初始参数了，如果占用还是不够再反馈给我吧

**Comment by CeeIM** [comment]
当前脚本更新时间(请注意比对仓库说明)： 2023.02.04
刚刚测试貌似还是不够，可能是脚本 CDN 还没更新？

**Comment by spiritLHLS** [comment]
> 当前脚本更新时间(请注意比对仓库说明)： 2023.02.04 刚刚测试貌似还是不够，可能是脚本 CDN 还没更新？ CPU 平均在 7-8，内存也不够，看不到太大变化。

晚上我看看，你是拿htop和top查看的么？用的是素数计算模式吧？

**Comment by spiritLHLS** [comment]
![图片](https://user-images.githubusercontent.com/103393591/216799333-04a3ca53-c3ac-4859-be1c-2b738ddabcbf.png)
![图片](https://user-images.githubusercontent.com/103393591/216799338-58e2ffe0-0340-4fea-b768-b1b396ce176e.png)
这边测试是正常的

**Comment by Saxon-Sun** [comment]
@spiritLHLS 可以增加一个更新脚本选项吗

**Comment by CeeIM** [comment]
> > 当前脚本更新时间(请注意比对仓库说明)： 2023.02.04 刚刚测试貌似还是不够，可能是脚本 CDN 还没更新？ CPU 平均在 7-8，内存也不够，看不到太大变化。
> 
> 晚上我看看，你是拿htop和top查看的么？用的是素数计算模式吧？且有等待超过10分钟并且历史记录的占用也不够么？ 别说是看某些第三方监控的，有的监控看不到占用的，但你htop或者top能看到

用 top 查看的，选的选项 1，到现在已经挂了 10 多个小时，依然还是占用不够。
![image](https://user-images.githubusercontent.com/18570103/216811731-c4c40925-0b0a-4951-8b69-3339ffe806ca.png)

**Comment by spiritLHLS** [comment]
> > > 当前脚本更新时间(请注意比对仓库说明)： 2023.02.04 刚刚测试貌似还是不够，可能是脚本 CDN 还没更新？ CPU 平均在 7-8，内存也不够，看不到太大变化。
> > 
> > 
> > 晚上我看看，你是拿htop和top查看的么？用的是素数计算模式吧？且有等待超过10分钟并且历史记录的占用也不够么？ 别说是看某些第三方监控的，有的监控看不到占用的，但你htop或者top能看到
> 
> 用 top 查看的，选的选项 1，到现在已经挂了 10 多个小时，依然还是占用不够。 ![image](https://user-images.githubusercontent.com/18570103/216811731-c4c40925-0b0a-4951-8b69-3339ffe806ca.png)

好家伙，行吧，我晚上再改改
问一句你这个服务器是不是4+24+200的？

> @spiritLHLS 可以增加一个更新脚本选项吗

这个卸载再安装就是新的了

**Comment by CeeIM** [comment]
> 问一句你这个服务器是不是4+24+200的？

@spiritLHLS ARM 4 + 24，硬盘 100 / 150 / 200 都有，正常的 AMD 机器测试没有问题。

**Comment by spiritLHLS** [comment]
> > 问一句你这个服务器是不是4+24+200的？
> 
> @spiritLHLS ARM 4 + 24，硬盘 100 / 150 / 200 都有，正常的 AMD 机器测试没有问题。

没测试过4+24的，我的问题
应该是需要针对核心数量去写参数和调参，目前只是动态调整没硬设置，核心数多的判断似乎失效了，可能是因为判断那里我读取的占用变成单核的了

**Comment by spiritLHLS** [comment]
> > > 当前脚本更新时间(请注意比对仓库说明)： 2023.02.04 刚刚测试貌似还是不够，可能是脚本 CDN 还没更新？ CPU 平均在 7-8，内存也不够，看不到太大变化。
> > 
> > 
> > 晚上我看看，你是拿htop和top查看的么？用的是素数计算模式吧？且有等待超过10分钟并且历史记录的占用也不够么？ 别说是看某些第三方监控的，有的监控看不到占用的，但你htop或者top能看到
> 
> 用 top 查看的，选的选项 1，到现在已经挂了 10 多个小时，依然还是占用不够。 ![image](https://user-images.githubusercontent.com/18570103/216811731-c4c40925-0b0a-4951-8b69-3339ffe806ca.png)

这里看到内存的free和used是没问题的，有问题的只是CPU占用

**Comment by spiritLHLS** [comment]
> > > 当前脚本更新时间(请注意比对仓库说明)： 2023.02.04 刚刚测试貌似还是不够，可能是脚本 CDN 还没更新？ CPU 平均在 7-8，内存也不够，看不到太大变化。
> > 
> > 
> > 晚上我看看，你是拿htop和top查看的么？用的是素数计算模式吧？且有等待超过10分钟并且历史记录的占用也不够么？ 别说是看某些第三方监控的，有的监控看不到占用的，但你htop或者top能看到
> 
> 用 top 查看的，选的选项 1，到现在已经挂了 10 多个小时，依然还是占用不够。 ![image](https://user-images.githubusercontent.com/18570103/216811731-c4c40925-0b0a-4951-8b69-3339ffe806ca.png)

![图片](https://user-images.githubusercontent.com/103393591/216815659-ab84b21f-02c5-4c6f-a342-165494b02ccc.png)

特殊处理了多核(3核或者4核)的情况，目前应该是占用够了(图片这里每个核不足10%没事，因为峰值是每个核12%，回落不够罢了，实际历史长期的记录应该是够的)

**Comment by Billtec** [comment]
@spiritLHLS 好像arm 4+24的机器CPU占用还是不够啊，每个core都只占用6%左右，在oracle cloud dashboard里面看cpu占用也是只有6%左右。
另外，怎么看网络是否有正常在占用？从dashboard里看好像并没有占用。。。

**Comment by CeeIM** [comment]
> @spiritLHLS 好像arm 4+24的机器CPU占用还是不够啊，每个core都只占用6%左右，在oracle cloud dashboard里面看cpu占用也是只有6%左右。 另外，怎么看网络是否有正常在占用？从dashboard里看好像并没有占用。。。

确实好像还不够，我这边历史统计 ARM 也是不到 8%，貌似要每个核心都达到 10% 以上才算达标，而不是每个核心相加总和。

**Comment by spiritLHLS** [comment]
> > @spiritLHLS 好像arm 4+24的机器CPU占用还是不够啊，每个core都只占用6%左右，在oracle cloud dashboard里面看cpu占用也是只有6%左右。 另外，怎么看网络是否有正常在占用？从dashboard里看好像并没有占用。。。
> 
> 确实好像还不够，我这边历史统计 ARM 也是不到 8%，貌似要每个核心都达到 10% 以上才算达标，而不是每个核心相加总和。

行吧，我再调高点

> @spiritLHLS 好像arm 4+24的机器CPU占用还是不够啊，每个core都只占用6%左右，在oracle cloud dashboard里面看cpu占用也是只有6%左右。 另外，怎么看网络是否有正常在占用？从dashboard里看好像并没有占用。。。

知道了

**Comment by spiritLHLS** [comment]
已增加占用，核数为2，3，4时占用限制为核数乘以15%，这样应该够了吧

**Comment by CeeIM** [comment]
> 已增加占用，核数为2，3，4时占用限制为核数乘以15%，这样应该够了吧

ARM CPU 占用已测试没问题，内存好像还是没变化，也是 ARM。

**Comment by spiritLHLS** [comment]
> > 已增加占用，核数为2，3，4时占用限制为核数乘以15%，这样应该够了吧
> 
> ARM CPU 占用已测试没问题，内存好像还是没变化，也是 ARM。

系统是Ubuntu，Debian么？可否htop截图我看看？

**Comment by Billtec** [comment]
> > > 已增加占用，核数为2，3，4时占用限制为核数乘以15%，这样应该够了吧
> > 
> > 
> > ARM CPU 占用已测试没问题，内存好像还是没变化，也是 ARM。
> 
> 系统是Ubuntu，Debian么？可否htop截图我看看？

系统是Ubuntu，好像脚本占用的内存是到Cached RAM里去了，所以在MobaXTerm的状态栏里内存占用比较小，不过htop里面看到的内存占用倒是有超过20%（5.25G/23.4G），不知道这种情况是否满足保活要求？
PS：Oracle Cloud 控制台里的度量表显示的内存占用是有达到20%。

**Comment by spiritLHLS** [comment]
> > > > 已增加占用，核数为2，3，4时占用限制为核数乘以15%，这样应该够了吧
> > > 
> > > 
> > > ARM CPU 占用已测试没问题，内存好像还是没变化，也是 ARM。
> > 
> > 
> > 系统是Ubuntu，Debian么？可否htop截图我看看？
> 
> 系统是Ubuntu，好像脚本占用的内存是到Cached RAM里去了，所以在MobaXTerm的状态栏里内存占用比较小，不过htop里面看到的内存占用倒是有超过20%（5.25G/23.4G），不知道这种情况是否满足保活要求？ PS：Oracle Cloud 控制台里的度量表显示的内存占用是有达到20%。

那就是足够了的，不一定要是used的
