### ISSUE TITLE
建议一种模式：cpu、内存交替占用

### ISSUE THREAD

**Issue by gnz1123** [spiritLHLS/Oracle-server-keep-alive-script#7]
交替时间间隔大一些有空闲期，占用比甲骨文的要求略高一些就好，避免过于激进鸡没保住号也让甲骨文收了。

**Comment by spiritLHLS** [comment]
实际上CPU和内存占用不会互相影响，而且资源占用比率很低吧，这方面没有风险吧
如果出现高负载欢迎告知
