### ISSUE TITLE
大佬 这个咋回事？？？

### ISSUE THREAD

**Issue by LoveForeverBoa** [spiritLHLS/Oracle-server-keep-alive-script#8]
== AUTHENTICATING FOR org.freedesktop.systemd1.manage-unit-files ===
Authentication is required to manage system service or unit files.
Authenticating as: Ubuntu (ubuntu)
Password: Failed to enable unit: Connection timed out
polkit-agent-helper-1: pam_authenticate failed: Authentication failure
==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ===
Authentication is required to start 'cpu-limit.service'.
Authenticating as: Ubuntu (ubuntu)
Password:
Password:
polkit-agent-helper-1: pam_authenticate failed: Authentication failure
==== AUTHENTICATION FAILED ===
Failed to reload daemon: Access denied
==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-unit-files ===
Authentication is required to manage system service or unit files.
Authenticating as: Ubuntu (ubuntu)
Password: Failed to enable unit: Connection timed out
polkit-agent-helper-1: pam_authenticate failed: Authentication failure
==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ===
Authentication is required to start 'cpu-limit.service'.
Authenticating as: Ubuntu (ubuntu)

**Comment by spiritLHLS** [comment]
我去，还有不启用root执行的？

**Comment by spiritLHLS** [comment]
你要在root权限下执行脚本

**Comment by spiritLHLS** [comment]
脚本增加了root判断，不使用root无法执行
